[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi   ; enable OPI PSRAM
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDEV_SECRETS
lib_deps =
  bblanchon/ArduinoJson@^7
  lvgl/lvgl@^8.4
  bodmer/TJpg_Decoder@^1.1
  jgromes/RadioLib@^6
  mikalhart/TinyGPSPlus@^1.0
extra_scripts = pre:scripts/gen_secrets.py

[env:smoke]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDEV_SECRETS
build_src_filter = -<*> +<smoke/>
lib_deps =
  bblanchon/ArduinoJson@^7
extra_scripts = pre:scripts/gen_secrets.py

[env:native]
platform = native
test_framework = unity
build_flags = -DNATIVE_TEST -std=gnu++17
extra_scripts = pre:build_native.py
lib_deps =
  bblanchon/ArduinoJson@^7
